### ISSUE TITLE
[IMPROVEMENT] Blue highlight on click

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/Arito#45]
## What improvement are you suggesting?
We should remove this blue highlight that appears when we click on links/buttons.

## Why should make this improvement?
It annoys the user.

## How can we make these improvements?
You can add:
```css
-webkit-tap-highlight-color: transparent;
```
You can also add this to your stylesheets to define it globally:

```css
input,
textarea,
button,
select,
a {
  -webkit-tap-highlight-color: rgba(0,0,0,0);
}
```
Source: [Stackoverflow](https://stackoverflow.com/a/45050338/13515764)

## Additional Context
| <img src="https://user-images.githubusercontent.com/65062036/205330427-45656bf7-6f2a-40f1-b723-590057733e8e.jpg" width="300px"> |
| --- |
